### ISSUE TITLE
forgot password is sending wrong token 

### ISSUE THREAD

**Issue by Jehfkemsy** [UPE-FIU/Turtle#34]
think you have some async issue going on... the reset password is not emailing the newly created token, it's sending the previously stored one or null

**Comment by Tommy2016x** [comment]
right now we have the mailing service setup to accept a single param and desctructure the those properties as seen here: https://github.com/UPE-FIU/Turtle/blob/master/src/services/mail.js#L171

however when we call the service we pass in two parameters when we should be passing in an object with the appropriate properties to desctructure. 
https://github.com/UPE-FIU/Turtle/blob/master/src/controllers/application.js#L471

so it should look something like this: 

```javascript
mailerService.forgotPassword({email, firstName, lastName, resetPasswordToken})
```

make sure you guys are calling the functions properly, this should have come up when testing it out
