### ISSUE TITLE
Registration route no longer works

### ISSUE THREAD

**Issue by Jehfkemsy** [UPE-FIU/Turtle#39]
**Describe the bug**
@Barnes2197  Registration route is not working... not sure if you tested them before your pr yesterday.
Also, you are not returning any error message when a request fails

**To Reproduce**
1. start-server
2. hit registration route
3. check your console

**Expected behavior**
return success message and send a token to the user

**Screenshots**
Getting this eror
`(node:7324) UnhandledPromiseRejectionWarning: ReferenceError: fields is not defined
    at fields (C:\Users\Jehf Denezaire\Documents\GitHub\Turtle\build\webpack:\src\controllers\application.js:125:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Additional context**

**Comment by Jehfkemsy** [comment]
think you have an infinite-ish loop in there... I made a bunch of requests and they all take about 3mins to get processed 

![alt text](https://cdn.discordapp.com/attachments/399368683828281346/605493366029025290/Capture.PNG "Logo Title Text 1")

**Comment by Barnes2197** [comment]
Issue was fixed
